In [1]:
import numpy as np

### Construção de Array unidimensionais e multidimensionais

In [2]:
#Construção de Array Unidimensional:
unid_array = np.arange(1,11)

#Construção de Array Multidimensional:
multd_array = np.array([np.arange(10),np.arange(11,21)])

In [3]:
#print array Unidimensional:
unid_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
#print array Multidimensional:
multd_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

### Slicing e indexação

In [5]:
# Array Unidimensional

#pegando o primeiro elemento do array:
print(f'o primeiro elemento do array Unidimensional: {unid_array[0]}')

#pegando os 3 ultimos elementos do array:
print(f'\nos 3 ultimos elementos do array: {unid_array[-3:]}')

# Array Multidimensional:

#pegando o primeiro elemento da linha e primeira coluna:
multd_array[0][0]
print(f'\no primeiro elemento da linha e primeira coluna: {multd_array[0][0]}')
#pegando os 3 ultimos elementos de cada linha:
multd_array[0:,7:]
print(f'\nos 3 ultimos elementos de cada linha:\n {multd_array[0:,7:]}')

o primeiro elemento do array Unidimensional: 1

os 3 ultimos elementos do array: [ 8  9 10]

o primeiro elemento da linha e primeira coluna: 0

os 3 ultimos elementos de cada linha:
 [[ 7  8  9]
 [18 19 20]]


### Operações com arrays (lógicas, aritméticas e algébricas)

In [7]:
#Criando uma cópias dos arrays:
_unid_array= unid_array.copy()
_multd_array=multd_array.copy()

#multiplicação:
print(f' unid_array * unid_array: {_unid_array * _unid_array}\n')
print(f'multd_array * multd_array: {_multd_array * _multd_array}\n')

#soma:
print(f' unid_array + unid_array: {_unid_array + _unid_array}\n')
print(f' multd_array + multd_array: {_multd_array + _multd_array}\n')

#Subtração:
print(f' unid_array - unid_array: {_unid_array - _unid_array}\n')
print(f' multd_array - multd_array: {_multd_array - _multd_array}\n')

#Raiz quadrada:
print(f' sqrt(unid_array) : {_unid_array**(1/2)}\n')
print(f' sqrt(multd_array) : {_multd_array**(1/2)}\n')

 unid_array * unid_array: [  1   4   9  16  25  36  49  64  81 100]

multd_array * multd_array: [[  0   1   4   9  16  25  36  49  64  81]
 [121 144 169 196 225 256 289 324 361 400]]

 unid_array + unid_array: [ 2  4  6  8 10 12 14 16 18 20]

 multd_array + multd_array: [[ 0  2  4  6  8 10 12 14 16 18]
 [22 24 26 28 30 32 34 36 38 40]]

 unid_array - unid_array: [0 0 0 0 0 0 0 0 0 0]

 multd_array - multd_array: [[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]

 sqrt(unid_array) : [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]

 sqrt(multd_array) : [[0.         1.         1.41421356 1.73205081 2.         2.23606798
  2.44948974 2.64575131 2.82842712 3.        ]
 [3.31662479 3.46410162 3.60555128 3.74165739 3.87298335 4.
  4.12310563 4.24264069 4.35889894 4.47213595]]



### Principais métodos utilizados pelos objetos Numpy

In [8]:
# cria um array com todos os elementos sendo 0
print( np.zeros(10))

# cria um array com todos os elementos sendo 1
print( np.ones(10))

# cria um array cujo conteúdo inicial é aleatório.
print( np.empty(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### Funções universais e estatísticas com Numpy

In [10]:
e = np.random.randn(5, 4)
print(e)

# Média:
print(f'\nMédia do array : {e.mean()}')

#soma:
print(f'\nSoma do array : {e.sum()}')

#Desvio padrão:std
print(f'\nDesvio padrão do array : {e.std()}')


[[ 1.13951041  1.46293531 -0.05370565 -0.97890888]
 [ 0.37697063  0.64703158 -0.87133592  0.74516674]
 [ 1.25813868  0.58474957  0.27020366 -0.33059844]
 [-0.34517862 -0.22980436  0.93340705  0.89834248]
 [-3.22872402  0.08269715  0.14451898  1.26662396]]

Média do array : 0.1886020164947564

Soma do array : 3.772040329895128

Desvio padrão do array : 1.0386950678475646


In [11]:
import pandas as pd

In [12]:
#Data Frame
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

df = pd.DataFrame(data)

In [14]:
df['year']*2

0    4000
1    4002
2    4004
3    4002
4    4004
5    4006
Name: year, dtype: int64

In [15]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
print(obj2 * 2)

d     8
b    14
a   -10
c     6
dtype: int64


In [20]:
df.min()

state    Nevada
year       2000
pop         1.5
dtype: object